import { describe, expect, it } from 'vitest'
import { MAX_LINES, MIN_LINES, validateChallenge } from '../../../scripts/validate.ts'
import bundle from '../generated/challenges.json'

/**
 * The seed validator is the only thing standing between a broken snippet and the
 * players, so each rule gets a test that proves it actually rejects — a
 * validator that silently passes everything looks identical to a working one.
 */

const VALID_CODE = Array.from({ length: 12 }, (_, i) => `const line${i} = ${i};`).join('\n')

function challenge(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    id: '11111111-1111-4111-8111-111111111111',
    language: 'javascript',
    difficulty: 2,
    category: 'off-by-one',
    code: VALID_CODE,
    bugLine: 3,
    explanation: 'A perfectly reasonable explanation of the observable failure.',
    source: 'handwritten',
    active: true,
    ...overrides,
  }
}

const VALID_PATH = 'javascript/off-by-one/example.json'

function check(
  raw: unknown,
  relPath = VALID_PATH,
  seenIds = new Map<string, string>(),
): string[] {
  return validateChallenge({ relPath, raw, seenIds })
}

describe('validateChallenge — accepts good content', () => {
  it('passes a well-formed snippet', () => {
    expect(check(challenge())).toEqual([])
  })

  it('passes every real snippet in content/', async () => {
    // Guards against a rule that is so strict it rejects the shipped content.
    const modules = import.meta.glob('../../../content/**/*.json', {
      eager: true,
      import: 'default',
    })
    const files = Object.entries(modules)

    expect(files.length).toBeGreaterThan(0)

    const seenIds = new Map<string, string>()
    for (const [path, raw] of files) {
      const relPath = path.split('/content/')[1] ?? path
      expect({ relPath, errors: check(raw, relPath, seenIds) }).toEqual({ relPath, errors: [] })
    }
  })
})

describe('the shipped bundle contains only the guest pool', () => {
  // This is a security invariant, not a preference. Anything in the bundle has
  // its answer readable from the extension. If a scored (server-pool) snippet
  // ever leaked into it, a signed-in player could read that challenge's bug line
  // out of the bundle and top the leaderboard with it.
  const contentModules = import.meta.glob('../../../content/**/*.json', {
    eager: true,
    import: 'default',
  })
  const all = Object.values(contentModules) as Record<string, unknown>[]

  // The bundle scripts/seed.ts --emit produced. Regenerated by the pretest hook.
  const bundled = bundle as { id: string }[]

  it('has snippets in both pools to begin with', () => {
    expect(all.some((c) => c['guest'] === true)).toBe(true)
    expect(all.some((c) => c['guest'] !== true)).toBe(true)
  })

  it('bundles every guest snippet and nothing else', () => {
    const guestIds = all.filter((c) => c['guest'] === true).map((c) => c['id'] as string).sort()
    const bundledIds = bundled.map((c) => c.id).sort()

    expect(bundledIds).toEqual(guestIds)
  })

  it('leaks no scored snippet into the bundle', () => {
    const scoredIds = new Set(all.filter((c) => c['guest'] !== true).map((c) => c['id'] as string))
    const leaked = bundled.filter((c) => scoredIds.has(c.id)).map((c) => c.id)

    expect(leaked).toEqual([])
  })

  it('strips the build-time guest flag from what ships', () => {
    for (const c of bundled) {
      expect(c).not.toHaveProperty('guest')
    }
  })
})

describe('validateChallenge — rejects bad content', () => {
  const cases: { name: string; input: unknown; relPath?: string; expect: RegExp }[] = [
    { name: 'not an object', input: ['nope'], expect: /must be a JSON object/ },
    { name: 'id is not a uuid', input: challenge({ id: 'abc' }), expect: /id must be a uuid/ },
    // Not 'rust' — that IS a language now. Pick one Bugsy genuinely does not run,
    // or this test quietly stops testing anything the day the language is added.
    { name: 'unknown language', input: challenge({ language: 'cobol' }), expect: /language must be one of/ },
    { name: 'unknown category', input: challenge({ category: 'vibes' }), expect: /category must be one of/ },
    { name: 'difficulty 0', input: challenge({ difficulty: 0 }), expect: /difficulty must be 1, 2 or 3/ },
    { name: 'difficulty 4', input: challenge({ difficulty: 4 }), expect: /difficulty must be 1, 2 or 3/ },
    { name: 'stub explanation', input: challenge({ explanation: 'nope' }), expect: /explanation must be a real sentence/ },
    { name: 'missing source', input: challenge({ source: '' }), expect: /source is required/ },
    { name: 'active not boolean', input: challenge({ active: 'yes' }), expect: /active must be a boolean/ },
    { name: 'missing code', input: challenge({ code: '' }), expect: /code is required/ },
    {
      name: 'too few lines',
      input: challenge({ code: 'a\nb\nc' }),
      expect: new RegExp(`code must be ${MIN_LINES}-${MAX_LINES} lines, got 3`),
    },
    {
      name: 'too many lines',
      input: challenge({ code: Array.from({ length: MAX_LINES + 1 }, () => 'x();').join('\n') }),
      expect: new RegExp(`code must be ${MIN_LINES}-${MAX_LINES} lines`),
    },
    { name: 'tabs in code', input: challenge({ code: VALID_CODE.replace('const', '\tconst') }), expect: /must use spaces, not tabs/ },
    { name: 'bugLine below range', input: challenge({ bugLine: 0 }), expect: /outside the snippet/ },
    { name: 'bugLine past end', input: challenge({ bugLine: 999 }), expect: /outside the snippet/ },
    { name: 'bugLine not an integer', input: challenge({ bugLine: 2.5 }), expect: /bugLine must be an integer/ },
    {
      name: 'bugLine on a blank line',
      input: challenge({ code: `const a = 1;\n\n${Array.from({ length: 10 }, () => 'x();').join('\n')}`, bugLine: 2 }),
      expect: /points at a blank line/,
    },
    {
      name: 'code gives the answer away in a comment',
      input: challenge({ code: `// this is the bug\n${VALID_CODE}` }),
      expect: /gives the bug away/,
    },
    {
      name: 'folder disagrees with language',
      input: challenge(),
      relPath: 'python/off-by-one/example.json',
      expect: /file is under python\/ but language is "javascript"/,
    },
    {
      name: 'folder disagrees with category',
      input: challenge(),
      relPath: 'javascript/scope/example.json',
      expect: /file is under scope\/ but category is "off-by-one"/,
    },
    {
      name: 'file not nested under language/category',
      input: challenge(),
      relPath: 'example.json',
      expect: /must live at content\/\{language\}\/\{category\}/,
    },
  ]

  for (const c of cases) {
    it(`rejects: ${c.name}`, () => {
      const errors = check(c.input, c.relPath ?? VALID_PATH)
      expect(errors.join('\n')).toMatch(c.expect)
    })
  }

  it('rejects a duplicate id and names the file that already claimed it', () => {
    const seenIds = new Map<string, string>()

    expect(check(challenge(), 'javascript/off-by-one/first.json', seenIds)).toEqual([])

    const errors = check(challenge(), 'javascript/off-by-one/second.json', seenIds)
    expect(errors.join('\n')).toMatch(/duplicate id, also used by javascript\/off-by-one\/first\.json/)
  })

  it('reports every problem at once, not just the first', () => {
    const errors = check(challenge({ id: 'x', difficulty: 9, source: '' }))
    expect(errors.length).toBeGreaterThanOrEqual(3)
  })
})
